name: æ–‡æ¡£éƒ¨ç½² ğŸ

on:
  push:
    branches:
      # ç¡®ä¿è¿™æ˜¯ä½ æ­£åœ¨ä½¿ç”¨çš„åˆ†æ”¯åç§°
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout âœ¨
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # å¦‚æœä½ æ–‡æ¡£éœ€è¦ Git å­æ¨¡å—ï¼Œå–æ¶ˆæ³¨é‡Šä¸‹ä¸€è¡Œ
          # submodules: true

      - name: è®¾ç½® Node.js ğŸ®
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: å®‰è£…ä¾èµ– âœ”
        run: npm ci

      - name: æ„å»ºæ–‡æ¡£ ğŸ§¸
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll
      - name: éƒ¨ç½²æ–‡æ¡£ ğŸ‰
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # è¿™æ˜¯æ–‡æ¡£éƒ¨ç½²åˆ°çš„åˆ†æ”¯åç§°
          branch: gh-pages
          folder: src/.vuepress/dist
